### ISSUE TITLE
Any chance of licensing this under Apache 2.0?

### ISSUE THREAD

**Issue by kerlyn-bsd3** [bitnami/wait-for-port#14]
### What is the problem this feature will solve?

AFAICT, bitnami charts and containers files are licensed under Apache2.0. Having the odd GPL'd component makes it more difficult to use the bitnami project.

### What is the feature you are proposing to solve the problem?

Re-license under Apache 2.0

**Comment by marcosbc** [comment]
Hi @kerlyn-bsd3, thanks for the suggestion!

After some checking, it seems like these are the only tools in the Bitnami org licensed as GPL: [gonit](https://github.com/bitnami/gonit), [ini-file](https://github.com/bitnami/ini-file), [render-template](https://github.com/bitnami/render-template) and [wait-for-port](https://github.com/bitnami/wait-for-port).

Given that we have standarized on using Apache 2.0 across all our other projects (except forks), we agree that it makes sense to re-license those projects to that license, and we are already working on it!
