### ISSUE TITLE
Please provide binary releases for the major platforms

### ISSUE THREAD

**Issue by PiotrOwsiak** [bitnami/wait-for-port#27]
### What is the problem this feature will solve?

People will be able to use the tool without cloning the repo and installing go on their machines, which I'm guessing is a deal breaker for many. I'm considering other options due to this "problem" cause I don't want to install Go tooling on my machine just to use this tool.

### What is the feature you are proposing to solve the problem?

Just create binary releases for the 3 major platforms: Linux, Windows and Mac so that people can download the tool and not be forced to build it on their own spending extra time and installing stuff they don't necessarily want or can on their machines.

### What alternatives have you considered?

An alternative is to go find an alternative to this tool :)

**Comment by javsalgar** [comment]
Thank you so much for the request! I will forward it to the team for consideration

**Comment by beltran-rubo** [comment]
wait-for-port tool has been developed and tested for Linux platforms so the support for OS X or Windows would be experimental, that is why those binaries are not part of the GitHub release.
