### ISSUE TITLE
make[1]: *** [get-build-deps] Error 1

### ISSUE THREAD

**Issue by czhfe** [bitnami/wait-for-port#3]
Error returned at compile time

![image](https://user-images.githubusercontent.com/19341806/130017804-67fee124-7281-4770-a3b3-caa760d65c5e.png)

**Comment by javsalgar** [comment]
Hi, 

Which golang version are you using? We are using 1.9 in our CI/CD

**Comment by juamedgod** [comment]
Hi @czhfe, #4 should fix it. Could you check it?

**Comment by czhfe** [comment]
> 你好，
> 
> 您使用的是哪个 golang 版本？我们在 CI/CD 中使用 1.9

**Comment by czhfe** [comment]
> Hi,
> 
> Which golang version are you using? We are using 1.9 in our CI/CD

Using golang version 1.16

**Comment by czhfe** [comment]
> Hi @czhfe, #4 should fix it. Could you check it?

It's already done, very good.

**Comment by liam-verta** [comment]
@czhfe Could you close this issue if it is fixed?
