### ISSUE TITLE
Requesting a release with changes in master

### ISSUE THREAD

**Issue by shrutimehta2812** [bitnami/wait-for-port#6]
bitnami/wait-for-port version v1.0 has Go version 1.9 which has critical vulnerabilities. The master bitnami/wait-for-port has the version of Go updated to v1.16 which fixes some of the vulnerabilities. change ref : https://github.com/bitnami/wait-for-port/blob/9b30a4e89da0901fdbcab7e5d3d11ae5e7367b49/go.mod#L3

Can you please create a newer release version with the changes in master.

**Comment by jotamartos** [comment]
Hi @shrutimehta2812 ,

As I just mentioned in the [Redis issue you opened](https://github.com/bitnami/bitnami-docker-redis/issues/218#issuecomment-960633847), this tool was updated to use the latest Go version and the Redis solution was updated too to include the latest version of this tool.

Thanks for taking the time to report this issue.

**Comment by shrutimehta2812** [comment]
Hi @jotamartos , 

Thank you for fixing the issue.
